waymondo/hoardable

- README.md
- lib/hoardable/hoardable.rb
- lib/hoardable/model.rb
- lib/hoardable/source_model.rb
- lib/hoardable/version.rb
- sig/hoardable.rbs
- test/support/database.rb
- test/support/models.rb
- test/test_model.rb
* Allows for overriding configuration options on a per model level
* Introduces a configuration option for `version_updates`, so that one could opt into creating versions only on deletion, for example
> Introduce `hoardable_options` per model

- CHANGELOG.md
- README.md
- lib/generators/hoardable/templates/migration.rb.erb
- lib/generators/hoardable/templates/migration_6.rb.erb
- lib/hoardable/associations.rb
- lib/hoardable/source_model.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- test/test_model.rb
Untrashing a version will now insert a version for the untrash event with it's own temporal timespan. This simplifies the ability to query versions temporarily for when they were trashed or not. This changes, but corrects, temporal query results using `.at`.
Because of the above, a new operation enum value of "insert" was added. If you already have the `hoardable_operation` enum in your PostgreSQL schema, you can add it by executing the following SQL in a new migration: `ALTER TYPE hoardable_operation ADD VALUE 'insert';`.
Additionally an `.at` scope was added to the source model class as well, to flexibly query a model for the state of records of that type at a given datetime or time.
> Insert version upon `untrash!` and add `.at` to `SourceModel`

- CHANGELOG.md
- README.md
- lib/generators/hoardable/templates/migration.rb.erb
- lib/generators/hoardable/templates/migration_6.rb.erb
- lib/hoardable/associations.rb
- lib/hoardable/source_model.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- test/test_helper.rb
- test/test_migration_generator.rb
- test/test_model.rb
The `foreign_key` on the temporal `versions` tables used to derive their name from the i18n singularized table naming. This is now being changed universally to `hoardable_source_id`. The intent is to never leave room for conflict of foreign keys for existing relationships. This can be upgraded for existing versions tables by renaming the columns from their i18n model name derived column names to `hoardable_source_id`, i.e.:
```
rename_column :post_versions, :post_id, :hoardable_source_id
```
> use `hoardable_source_id` as the foreign key on `versions` tables

- .rubocop.yml
- CHANGELOG.md
- README.md
- lib/generators/hoardable/initializer_generator.rb
- lib/hoardable.rb
- lib/hoardable/associations.rb
- lib/hoardable/database_client.rb
- lib/hoardable/hoardable.rb
- lib/hoardable/scopes.rb
- lib/hoardable/source_model.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- sig/hoardable.rbs
- test/support/models.rb
- test/test_model.rb
`Hoardable.at` provides a high-level block form of doing cross resource temporal lookups. This replaces `Hoardable.return_everything` as a more useful and pointed tool.
`has_many_hoardable` provides a way to define an extended `has_many` association that can hook into into `Hoardable.at`'s temporal awareness.
A `.hoardable` scope is added to `Hoardable::Model`s that allow for finding the a relevant version or source record by providing just the source record's ID.
> Introduce `Hoardable.at`, `.hoardable`, `has_many_hoardable`

- README.md
- lib/generators/hoardable/templates/install.rb.erb
- lib/generators/hoardable/templates/migration.rb.erb
- lib/hoardable/belongs_to.rb
- lib/hoardable/database_client.rb
- lib/hoardable/finder_methods.rb
- lib/hoardable/has_many.rb
- lib/hoardable/scopes.rb
- lib/hoardable/source_model.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- test/test_helper.rb
- test/test_migration_generator.rb
- test/test_model.rb
This is made possible due to a schema change of moving what was once called `hoardable_source_id` on the versions table up to `hoardable_id` on the source model table. `hoardable_id` is set to `id` with a trigger on source model insertion and when a version is inserted, even though a new ID is generated, `hoardable_id` will remain as a stable reference to the original source record ID. Because the column is on both source and version tables, it makes queries across the parent and child tables easier to manage.
Due to the breaking change, any existing hoardable users will have to:
* Re-run the install migration generator
* Add and seed `hoardable_id` to existing hoardable tables
* Add the trigger to hoardable tables
I hope for this to be the last schema change before preparing the first …
> `has_many through` support

- lib/hoardable/error.rb
- lib/hoardable/has_one.rb
- lib/hoardable/version.rb
- test/test_model.rb
* fixes the association reflection lookup
* ensures all has one lookups happen temporally based on updated_at
* requires updated_at column on parent relationship
* adds test that has one lookups work on version records
> fix / improve `has_one` relationship

- lib/hoardable/database_client.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- test/support/database.rb
- test/support/models.rb
- test/test_model.rb
when using `attributes_before_type_cast` to insert an unpersisted attribute into the versions table, it doesn't process the attribute with the ActiveRecord serialization logic. instead let's fully lean on ActiveRecord to process the attributes hash correctly when calling `.insert`.
> fix untrashing record with serialized attributes

- README.md
- lib/hoardable/engine.rb
- lib/hoardable/scopes.rb
- lib/hoardable/version.rb
- sig/hoardable.rbs
- test/test_helper.rb
- test/test_model.rb
Since leaving a note could be considered part of the `meta` of a version, let's remove the global data handling for it and assume it will be handled via `meta`.
> spruce up README, remove `hoardable_note`, bump minor version

- CHANGELOG.md
- lib/generators/hoardable/templates/migration.rb.erb
- lib/hoardable/version.rb
- test/test_migration_generator.rb
according to the [Postgres docs](https://www.postgresql.org/docs/current/ddl-inherit.html):
```
Other types of constraints (unique, primary key, and foreign key constraints) are not inherited
```
this means that the `_versions` table id columns that inherit the parent table's sequence weren't actually considered the primary key column.
this change drops the unique index on the inherited table's primary key column and alters the descendant table to make it the primary column for the table instead.
> make the versions table primary key column the actual primary key

- .github/workflows/main.yml
- CHANGELOG.md
- Gemfile
- README.md
- Rakefile
- bin/console
- lib/generators/hoardable/install_generator.rb
- lib/generators/hoardable/templates/install.rb.erb
- lib/hoardable/engine.rb
- lib/hoardable/has_many.rb
- lib/hoardable/scopes.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- sig/hoardable.rbs
- test/config/application.rb
- test/helper.rb
- test/install_generator_test.rb
- test/support/database.rb
- test/support/models.rb
- test/test_helper.rb
- test/test_hoardable.rb
- test/test_migration_generator.rb
- test/test_model.rb
changes the default scoping clause that controls the inherited table SQL construction from a where clause using `tableoid`s to using `FROM ONLY`. this comes as a simplification, but is more performant as it can avoid sequential scans on the version tables. see [this issue](https://github.com/waymondo/hoardable/issues/30) for more information.
this version bump also drops support for Ruby 2.7 and Rails 6.1
closes #30
> replace `tableoid` where clause with `FROM ONLY`

- .github/workflows/main.yml
- CHANGELOG.md
- lib/hoardable/version_model.rb
- test/config/application.rb
enables the test suite for rails 7.1. also fixes a 7.1 issue where `alias_attribute` didn't work as expected for db columns that only existed on the version tables
> rails 7.1 test suite

- Rakefile
- hoardable.gemspec
- lib/hoardable.rb
- lib/hoardable/arel_visitors.rb
- lib/hoardable/engine.rb
- lib/hoardable/has_many.rb
- lib/hoardable/model.rb
- test/support/models.rb
- test/test_model.rb
it doesn't seem like there's a good way around the fact that currently `Arel` [isn't flexible about how SQL JOIN strings get constructed](https://github.com/rails/rails/blob/16ff9afb2e78346e51b8969b76fc6afcba69d860/activerecord/lib/arel/visitors/to_sql.rb#L549-L558) regarding allowing the `ONLY` keyword to be conditionally appended. ideally one day Arel might support this, but for now we can monkey patch these methods. it doesn't feel great, but these methods have been stable for many years at this point.
also includes a bit more noise regarding linting
> add monkey patch for joining with `ONLY` keyword

- lib/hoardable/has_rich_text.rb
we can’t load our Hoardable RichText subclasses until the ActionText ones have been, but if ActionText hasn’t been loaded yet, the `has_rich_text` extension can fail due to being unaware of them:
https://github.com/waymondo/hoardable/blob/717c5d5f2fede025491eaaf59f80d8c1253d69e1/lib/hoardable/engine.rb#L95-L98
connect to https://github.com/waymondo/hoardable/issues/37
> load the `ActionText` class if it hasn’t been already

- .streerc
- README.md
- lib/hoardable/has_rich_text.rb
- test/support/database.rb
- test/support/models.rb
- test/test_model.rb
IDEs that use the [RDoc options from Rails' source](https://github.com/rails/rails/blob/6b93fff8af32ef5e91f4ec3cfffb081d0553faf0/actiontext/lib/action_text/attribute.rb#L29) can complain that it doesn't know about the `hoardable:` option. This provides an alternate way to define a Hoardable rich text relationship.
connect to https://github.com/waymondo/hoardable/issues/37
> add `has_hoardable_rich_text` for `has_rich_text hoardable: true`

- lib/generators/hoardable/install_generator.rb
- lib/generators/hoardable/templates/install.rb.erb
- test/test_install_generator.rb
`gen_random_uuid()` is available by default in PG versions 13+, so we need to ensure it's enabled for older versions.
closes https://github.com/waymondo/hoardable/issues/39
> conditionally enable crypto during install based on PG version

- lib/hoardable/arel_visitors.rb
- lib/hoardable/version.rb
- test/support/models.rb
- test/test_model.rb
First of all, great library. We've just recently been using it in production and are really enjoying it.
One thing I've noticed is that Hoardable is not correctly injecting the `ONLY` clause when using a table alias.
For example - using the test DB schema as an example:
```
has_one :bio, class_name: "Profile"
```
When building a query using this alias, the `ArelVisitors` monkey patch is silently ignoring it because `o.left` is a table alias, which needs to be recursed into.
Anyway, here is a PR to fix that so Hoardable can properly support using aliases. 👍
> feat: Add support for table alias when injecting ONLY clause

- README.md
- lib/hoardable/database_client.rb
- lib/hoardable/engine.rb
- lib/hoardable/error.rb
- lib/hoardable/version.rb
- test/test_model.rb
This PR implements a `Hoardable.on` helper class method that allows calling code to influence the upper bound of the time range used to represent a change.
```ruby
post = Post.create(title: "Blah", created_at: 1.month.ago, updated_at: 1.month.ago)
Hoardable.on(2.weeks.ago) do
post.destroy!
end
PostVersion.last._during.max # -> 2.weeks.ago
```
I am more than happy for feedback on implementation and naming on this one!
It's a relatively obscure feature, of course, but it's something we've already found ourselves having to do as we begin to roll Hoardable out into a relatively large, in-production Rails app.
So, having the ability to influence that generated upper bound so it doesn't always hardcode to `Time.now.utc` is really helpful :)
> feat: Support custom temporal upper bound with Hoardable.on

- lib/generators/hoardable/templates/migration.rb.erb
- lib/hoardable/version.rb
This fixes the bug in which the generator is called with a nested model as input.
Previous functionality would generate a class name that did not match the file name, which would cause a zeitwerk error.
For example:
```
class My::Nested::Model
table_name :products
end
```
```
rails g hoardable:migration My::Nested::Model
```
This would use the table name to form the migration file name, but the class name to form the class name of the migration.
This PR is just a simple fix to ensure we use the table name in both the migration file name and the class name so they always match.
(FYI I am pretty sure I introduced this bug myself in a previous PR - sorry!)
> fix: Ensure the class name matches the file name in the migration generator

- README.md
- lib/generators/hoardable/migration_generator.rb
- lib/hoardable/model.rb
- lib/hoardable/scopes.rb
- lib/hoardable/source_model.rb
- lib/hoardable/version.rb
- lib/hoardable/version_model.rb
- test/support/database.rb
- test/support/models.rb
- test/test_model.rb
closes https://github.com/waymondo/hoardable/issues/51
adds basic support for [single table inheritance](https://guides.rubyonrails.org/association_basics.html#single-table-inheritance-sti). it does this by changing the parts that need to be re-evaluated in subclasses from using `ActiveSupport::Concern`'s `included` block, to using a regular call to the class's `included` method.
> basic STI support

- CHANGELOG.md
- lib/hoardable/arel_visitors.rb
- lib/hoardable/database_client.rb
- lib/hoardable/engine.rb
- lib/hoardable/has_many.rb
- lib/hoardable/scopes.rb
- lib/hoardable/version.rb
This adds support for thread-safety to Hoardable for:
- `with`
- `travel_to`
- `at`
This is important because production apps will run multiple threads and currently any overloading of `config` or `context` data (`event_uuid`, `whodunit`, etc) will occur globally across all threads, which will lead to data leaks.
Fixes: https://github.com/waymondo/hoardable/issues/63
> Feat: Allow for thread-safe configuration and context setting

- lib/hoardable/database_client.rb
- lib/hoardable/engine.rb
it doesn't make sense to store store a null entry for `_event_uuid` on `_data`. hoardable's database client manages setting `_event_uuid` for all records in the same thread's transaction on it's own column. also, it doesn't make much sense to request postgres to generate a UUID for the event when we can do that directly with ruby.
connect to https://github.com/waymondo/hoardable/issues/66
> `event_uuid` tweaks

- CHANGELOG.md
- Gemfile
- lib/hoardable/model.rb
- lib/hoardable/version.rb
- test/support/database.rb
- test/test_model.rb
- test/test_thread_safety.rb
follow up to #64, which adds thread-safety to the model's class method `with_hoardable_config` as well. also adds a new test file for thread safety checks.
closes https://github.com/waymondo/hoardable/issues/65
> thread safety for `with_hoardable_config`

- CHANGELOG.md
- lib/hoardable/scopes.rb
- lib/hoardable/version.rb
This fixes a bug in the Hoardable STI support where:
- Source table tas a `type` column
- Does not use STI
If the source table (let's say a `Question` model) has a `type` column, the default scope builder in Hoardable will incorrectly add it to the scope, which will break Hoardable on that model.
```
Question.where(bloo: "blah").where_clause.to_h # =>  {"type"=>"Question", "bloo"=>"blah"}
```
This also breaks Hoardable when it tries to `insert_version_record`, because the `type` column is overwritten with the source model class name.
Anyway, I am thinking it's happening because Hoardable is currently assuming the column name for STI on the source model is `type`. But actually it's whatever `inhertitance_column` is defined as.
So I reckon we should consult that value instead of hard-coding …
> fix: Ensure we consult the inheritance_column rather than assuming 'type'
